### ISSUE TITLE
learnedModel.LearningHistory empty

### ISSUE THREAD

**Issue by martinpfannemueller** [se-passau/SPLConqueror#40]
I have the problem that I get an InvalidOperationException in line 604 of Commands.cs:
`GlobalState.logInfo.logLine("Termination reason: " + learnedModel.LearningHistory.Last().terminationReason);`

The reason for that is that learnedModel.LearningHistory is empty. What could be the reason for this? In general this might also be something which could be checked instead of crashing. Thanks a lot for any idea!

**Comment by ChristianKaltenecker** [comment]
Hey,

Could you please provide further details? For instance, the automation script containing the commands for SPL Conqueror, the variability model and the measurement file would be useful for us to reproduce your problem.

And yes, as soon as we find the reason, we would implement a further check.

**Comment by ChristianKaltenecker** [comment]
Hey,

Thank you for your scripts. I was able to reproduce your situation.

The problem are the values of your NFP called 'mMatchedDeadlines'. By default, we compute the error of the models found by multiple linear regression relatively.
The formula is as follows: `(predictedNFPValue - realNFPValue) / realNFPValue * 100`
Since 'mMatchedDeadlines' has sometimes the value '0', the formula above will evaluate in 'Infinity'.
We will definitely add a check for this case.

To solve the problem, you can change from relative to absolute error computation by adding `lossFunction ABSOLUTE` to the machine-learning settings.
Another solution could be to increment all values of 'mMatchedDeadlines' by 1 and use relative error computation (if you want to stick with the relative error calculation).
You can try both solutions and stick with the better one.

Feel free to contact us if you face further problems with SPL Conqueror.

This issue will remain opened until the check is implemented.
